### ISSUE TITLE
collect_output fails with process_fact_data.py

### ISSUE THREAD

**Issue by tarrox** [fact-project/erna#57]
The `process_fact_data.py` fails while collecting the datasets. The problem is with line 102 in `erna/__init__.py` (in the `collect_output` function). For whatever reason the pd.Index(df) fails with the error that the given list is not hashable or something.

**Comment by jebuss** [comment]
I guess you meant line 84?

https://github.com/fact-project/erna/blob/5ee5f201b82090243bad8ba5caa93272e21df22f/erna/__init__.py#L75-L95

**Comment by tarrox** [comment]
Actually its line 102 fixed it in the first comment. Don't know what happend.

**Comment by MaxNoe** [comment]
This is fixed, right?

**Comment by tarrox** [comment]
Doesn't seem to be an issue anymore, so closing as it seems to work now.
