### ISSUE TITLE
collect_output fails with process_fact_data.py due to new fact_tools version

### ISSUE THREAD

**Issue by tarrox** [fact-project/erna#62]
The `process_fact_data.py` fails merging the `df_started_runs` with the `df_returned_data` on line 111 in `erna/__init__.py` (in the collect_output function). Basically in the new fact_tools processing we sanitize the keys into camel case which results in the key `night` and `run_id` which is different from the original `NIGHT` and `RUNID` which makes the merge impossible and everything breaks.

This needs to be fixed, question is how, as a change could mean that older versions of fact-tools xmls will fail. So either a backward compatible solution needs to be implemented or we just fix this and don't care.

**Comment by jebuss** [comment]
I guess you tested this with fact-tools-1.0?

**Comment by tarrox** [comment]
Yes. The bug is basically a result of the use of the new `SanatizeKeys` prozessor.

**Comment by tarrox** [comment]
This was fixed by #67, so closing it down.
